name: Input Demo

on: 
  workflow_dispatch:
    inputs:
      level:
        description: 'Ange ett nivåvärde'
        required: true
        type: number

jobs: 
  run-job: 
    if: ${{ fromJSON(github.event.inputs.level) >= 42 }}
    runs-on: ubuntu-latest
    steps:
      - name: Kör om nivå är tillräcklig
        run: echo "Nivå är ${{ fromJSON(github.event.inputs.level) }}, jobbet körs"
      
